language: python
sudo: required
cache: pip

services:
- postgresql
- rabbitmq

addons:
  postgresql: "10.6"

matrix:
  include:
    - python: 3.6
      env: TEST_TYPE="code-style"
    - python: 3.6
      env: TEST_TYPE="version"
    - python: 3.6
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django"
    - python: 2.7
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="django"
    - python: 3.6 
      env: TEST_TYPE="pytest" TEST_AIIDA_BACKEND="sqlalchemy"

  allow_failures:
    - env: TEST_TYPE="code-style"

before_install:

  # This installs a relatively old version of LAMMPS (11 Nov 2013)
  - if [[ "$TEST_TYPE" == "pytest" ]]; then sudo apt-get update -q; fi
  - if [[ "$TEST_TYPE" == "pytest" ]]; then sudo apt-get install lammps -y; fi

# Ideally we would want to run this, however, they are only built for debian-xenial not trusty
#  - sudo add-apt-repository ppa:gladky-anton/lammps -y
#  - sudo apt-get update -q
#  - sudo apt-get install lammps-stable -y

# This would be a more complex (and time consuming route)
#- git clone -b stable_22Aug2018 https://github.com/lammps/lammps.git lammps
#- cd lammps/src
#- make serial
#- ls
#- cd ../..

# get version of lammps
#  - if [[ "$TEST_TYPE" == "pytest" ]]; then lammps -h || true; fi

install:
- pip install -U pip wheel setuptools "reentry>=1.3"
- |
    if [[ "$TEST_TYPE" == "pytest" ]]; then
      pip uninstall -y numpy
      pip install -e .[testing]
      pip install coveralls
    fi
- |
    if [[ "$TEST_TYPE" == "code-style" ]]; then
      pip install "flake8<3.8.0,>=3.7.0"
    fi

before_script:
- |
    if [[ "$TEST_TYPE" == "pytest" ]]; then
      reentry scan
    fi

script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      pytest -v --cov=aiida_lammps --cov-report= aiida_lammps
  fi
- |
  if [[ "$TEST_TYPE" == "code-style" ]]; then
    flake8 aiida_lammps
  fi
- |
  if [[ "$TEST_TYPE" == "version" ]]; then
    python ./.travis-data/check_version.py
  fi

# after_success:
# - coveralls
